### ISSUE TITLE
Ice will no longer open: TypeError: Expected GObject

### ISSUE THREAD

**Issue by twizzay-code** [peppermintos/ice#89]
I have self-built ICE on debian following this guide: https://gist.github.com/fardjad/2483618d4833b3cd76deec272672ffeb

Everything was working great for a little while.
I am not sure what went wrong but at one point I was simply going along making a bunch of SSB's and having a wonderful time, and then suddenly Ice wouldn't open anymore...

I have tried uninstalling it and reinstalling it, and rebooting.

I found another issue on here that mentioned a profiles folder. For me, ~/twizzay/.local/share/ice/profiles exists.

### The problem

When I run ice in a terminal, the following appears:
```
Traceback (most recent call last):
  File "/usr/bin/ice", line 940, in <module>
    window = Ice()
  File "/usr/bin/ice", line 404, in __init__
    self.liststore.append([self.details['pixbuf'],
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 1004, in append
    return self._do_insert(-1, row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 995, in _do_insert
    row, columns = self._convert_row(row)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 902, in _convert_row
    result.append(self._convert_value(cur_col, value))
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 916, in _convert_value
    return GObject.Value(self.get_column_type(column), value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 208, in __init__
    self.set_value(py_value)
  File "/usr/lib/python3/dist-packages/gi/overrides/GObject.py", line 257, in set_value
    _gi._gvalue_set(self, py_value)
TypeError: Expected GObject
```

### System Specs
FWIW here is my neofetch I have no idea if it is useful here Not really sure how to troubleshoot. I am using ice 6.0.8.

```
       _,met$$$$$gg.          twizzay@debian
    ,g$$$$$$$$$$$$$$$P.       ---------
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 11 (bullseye) x86_64
 ,$$P'              `$$$.     Host: OptiPlex 3050
',$$P       ,ggs.     `$$b:   Kernel: 5.10.0-17-amd64
`d$$'     ,$P"'   .    $$$    Uptime: 1 hour, 1 min
 $$P      d$'     ,    $$P    Packages: 2811 (dpkg), 8 (flatpak)
 $$:      $$.   -    ,d$$'    Shell: bash 5.1.4
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080
 Y$$.    `.`"Y$$$$P"'         WM: i3
 `$$b      "-.__              Theme: Breeze [GTK2/3]
  `Y$$                        Icons: breeze-dark [GTK2/3]
   `Y$$.                      Terminal: mlterm
     `$$b.                    CPU: Intel i3-6100 (4) @ 3.700GHz
       `Y$$b.                 GPU: Intel HD Graphics 530
          `"Y$b._             Memory: 3075MiB / 7840MiB
              `"""
```

**Comment by twizzay-code** [comment]
The workaround for me was to start using Firefox profiles, since that's how Ice works anyway. Marking as complete.
